# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "aiohttp>=3.12.14,<4",
#     "playwright>=1.49,<2",
# ]
# ///
"""Writes docs/widgets.md and its pictures: every widget kind of
dashboard.toml, with what it says, the line that places it, and what it
looks like — the vocabulary a person (or an agent) uses to say how the
dashboard should look.

The pictures are the real page drawing the browser tests' fixture house
(tests/browser/fixtures, as the Pages demo edits it: people placed on the
map), one view per widget, so they show the dashboard
as it is rather than as it was once mocked up. The words come from
docs/manifest.md, which is generated from the parser itself; this script
adds no description of its own. src/schema.rs pins that every widget kind
the parser accepts has a section here, so a new kind cannot ship without
its picture.

Usage: uv run --script scripts/widget_gallery.py [--chromium PATH]
"""

import argparse
import asyncio
import json
import pathlib
import re
import sys

from playwright.async_api import async_playwright

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tests" / "browser"))
sys.path.insert(0, str(ROOT / "scripts"))
from build_demo_site import data
from server import FakeHouse

DOCS = ROOT / "docs"
PICTURES = DOCS / "widgets"

# One placing line per kind, against the fixture house. A group is shown
# around the two widgets it most often holds.
EXAMPLES = {
    "tile": {"kind": "tile", "entity": "spot"},
    "chart": {"kind": "chart", "entity": "livingroom_temp", "aspect": "temperature", "hours": 24},
    "entity": {"kind": "entity", "entity": "livingroom_lamp"},
    "dial": {"kind": "dial", "entity": "heat_pump"},
    "room": {"kind": "room", "room": "livingroom"},
    "unit": {"kind": "unit", "unit": "evening_lights"},
    "params": {"kind": "params", "unit": "evening_lights"},
    "people": {"kind": "people"},
    "deviations": {"kind": "deviations"},
    "map": {"kind": "map"},
    "group": {
        "kind": "group",
        "label": "Heating",
        "widgets": [
            {"kind": "dial", "entity": "heat_pump"},
            {"kind": "chart", "entity": "livingroom_temp", "aspect": "temperature", "hours": 24},
        ],
    },
    "burner": {"kind": "burner", "entity": "stove"},
}

KEY_ORDER = ["kind", "entity", "aspect", "room", "unit", "label", "hours"]


def toml_widget(widget: dict, indent: str = "") -> str:
    """The widget as dashboard.toml writes it — the same shape the page's
    "Text" overlay prints (dashboard-logic.js, viewText)."""
    fields = [
        f"{k} = {json.dumps(widget[k])}"
        for k in sorted((k for k in widget if k != "widgets"), key=KEY_ORDER.index)
    ]
    if "widgets" not in widget:
        return f"{indent}{{ {', '.join(fields)} }}"
    members = "".join(toml_widget(m, indent + "  ") + ",\n" for m in widget["widgets"])
    return f"{indent}{{ {', '.join(fields + ['widgets = ['])}\n{members}{indent}] }}"


def kinds_from_manifest() -> list[tuple[str, str]]:
    """(kind, description) in the parser's order, from the WidgetKind
    section of docs/manifest.md."""
    text = (DOCS / "manifest.md").read_text()
    section = text.split("### WidgetKind", 1)[1].split("\n## ", 1)[0]
    return re.findall(r"^- `([a-z]+)` — (.+)$", section, re.MULTILINE)


async def pictures(chromium: str | None) -> None:
    house = FakeHouse()
    # The Pages demo's edit of the fixtures: the people placed on the map,
    # no camera without a stream to show.
    demo = data()
    house.model, house.snapshot = demo["model"], demo["snapshot"]
    url = await house.start()
    PICTURES.mkdir(exist_ok=True)
    try:
        async with async_playwright() as pw:
            browser = await pw.chromium.launch(**({"executable_path": chromium} if chromium else {}))
            context = await browser.new_context(
                viewport={"width": 460, "height": 900},
                device_scale_factor=2,
                color_scheme="light",
                timezone_id="Europe/Stockholm",
                locale="en-GB",
            )
            page = await context.new_page()
            for kind, widget in EXAMPLES.items():
                house.model = dict(house.model, views=[{"name": "gallery", "widgets": [widget]}])
                await page.goto(url)
                await page.wait_for_timeout(1500)
                await page.locator("#view .grid").screenshot(path=PICTURES / f"{kind}.png")
            await browser.close()
    finally:
        await house.stop()


def markdown(kinds: list[tuple[str, str]]) -> str:
    out = [
        "# Dashboard widgets",
        "",
        "<!-- Generated by scripts/widget_gallery.py; edit that, not this. -->",
        "",
        "The words for saying how the dashboard should look. A view in",
        "`dashboard.toml` is a list of widgets, and each widget places something",
        "the house already has; the dashboard draws it. These are all of them,",
        "drawn from the browser tests' fixture house. Every field each one takes",
        "is in [manifest.md](manifest.md#widgetspec), and the dashboard shows",
        "the text behind any view (its **Text** button).",
        "",
        "A request in these words — \"on the heating view, put a `dial` for the",
        "heat pump in a `group` with a 24-hour `chart` of the living-room",
        "temperature\" — maps onto the file one widget at a time.",
        "",
    ]
    for kind, description in kinds:
        example = EXAMPLES[kind]
        out += [
            f"## `{kind}`",
            "",
            description,
            "",
            "```toml",
            toml_widget(example),
            "```",
            "",
            f"![The {kind} widget]({PICTURES.name}/{kind}.png)",
            "",
        ]
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--chromium", help="a Chromium to drive instead of Playwright's own")
    args = parser.parse_args()
    kinds = kinds_from_manifest()
    missing = [k for k, _ in kinds if k not in EXAMPLES]
    if missing:
        sys.exit(f"widget_gallery: no example for {', '.join(missing)}; add one to EXAMPLES")
    asyncio.run(pictures(args.chromium))
    (DOCS / "widgets.md").write_text(markdown(kinds))
    print(f"wrote docs/widgets.md and {len(kinds)} pictures")


if __name__ == "__main__":
    main()
